# -*- coding: utf-8 -*-
"""compare_zero_shot_vs_finetuned

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vRDl9sJRLM2BKk2_2B62dUuo45eIpj0j
"""

from sklearn.metrics import classification_report, accuracy_score
import pandas as pd
import matplotlib.pyplot as plt

# Step 1: Classification Reports
print("Zero‑Shot Accuracy:", accuracy_score(true_labels_zs, pred_labels_zs))
print("\nZero‑Shot Classification Report:")
report_zs = classification_report(true_labels_zs, pred_labels_zs, target_names=le.classes_.astype(str), output_dict=True)
print(classification_report(true_labels_zs, pred_labels_zs, target_names=le.classes_.astype(str)))

print("\nFine‑Tuned Accuracy:", accuracy_score(true_labels_zs, pred_labels_ft))
print("\nFine‑Tuned Classification Report:")
report_ft = classification_report(true_labels_zs, pred_labels_ft, target_names=le.classes_.astype(str), output_dict=True)
print(classification_report(true_labels_zs, pred_labels_ft, target_names=le.classes_.astype(str)))

# Step 2: F1-Score Comparison Table
comparison = pd.DataFrame({
    "Zero-Shot F1": {label: report_zs[label]["f1-score"] for label in le.classes_},
    "Fine-Tuned F1": {label: report_ft[label]["f1-score"] for label in le.classes_},
})
comparison["Difference"] = comparison["Fine-Tuned F1"] - comparison["Zero-Shot F1"]

print("\n🔍 F1-Score Comparison:")
print(comparison)

# Optional: Accuracy Bar Chart
comparison[["Zero-Shot F1", "Fine-Tuned F1"]].plot(kind='bar', figsize=(10, 6), title='F1 Score Comparison: Zero-Shot vs Fine-Tuned')
plt.ylabel('F1 Score')
plt.xticks(rotation=0)
plt.grid(axis='y')
plt.tight_layout()
plt.show()